Practica6/app/app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restaurantes/', include('restaurantes.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

Practica6/app/restaurantes/forms.py
# restaurantes/forms.py

from django import forms
from django.core.exceptions import ValidationError

def validate_postal_code(value):
    if value < 10000 or value > 99999:
        raise ValidationError('%s no parece ser un código postal' % value)

class RestaurantForm(forms.Form):
    name = forms.CharField(
        label='Nombre',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Nombre',
        })
    )

    street = forms.CharField(
        label='Calle',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Calle',
        })
    )

    building = forms.IntegerField(
        label='Número'
    )

    borough = forms.CharField(
        label='Barrio',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Barrio',
        })
    )

    cuisine = forms.CharField(
        label='Tipo',
        max_length=80,
        required=False,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Mejicana',
        })
    )

    zipcode = forms.IntegerField(
        label='Código Postal',
        validators=[validate_postal_code]
    )

class RestaurantEditForm(forms.Form):
    restaurant_id = forms.IntegerField(
        label='Id',
        widget=forms.TextInput(
            attrs={ 'size': 30,
                    'id': 'restaurant_id',
                    'placeholder':'Id',
        })
    )

    name = forms.CharField(
        label='Nombre',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Nombre',
        })
    )

    street = forms.CharField(
        label='Calle',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Calle',
        })
    )

    building = forms.IntegerField(
        label='Número'
    )

    borough = forms.CharField(
        label='Barrio',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Barrio',
        })
    )

    cuisine = forms.CharField(
        label='Tipo',
        max_length=80,
        required=False,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Mejicana',
        })
    )

    zipcode = forms.IntegerField(
        label='Código Postal',
        validators=[validate_postal_code]
    )

class RestaurantFindForm(forms.Form):
    CHOICES = (('Cuisine', 'Cuisine'),
                ('Borough', 'Borough'),
                ('Name', 'Name'),
                ('Zip', 'Zip'),)
    field = forms.ChoiceField(choices=CHOICES)

    borough = forms.CharField(
        label='Barrio',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Barrio',
        })
    )

    cuisine = forms.CharField(
        label='Tipo',
        max_length=80,
        required=False,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Mejicana',
        })
    )

    zipcode = forms.IntegerField(
        label='Código Postal',
        validators=[validate_postal_code]
    )

    name = forms.CharField(
        label='Nombre',
        max_length=60,
        strip=True,
        widget=forms.TextInput(
            attrs={ 'size':30,
                    'placeholder':'Nombre',
        })
    )

Practica6/app/templates/forms/create_restaurant.html
{% extends 'layout.html' %}
{% block body %}
  <section class="default_section">
    <h1>Registra tu restaurante</h1>
    <div class="pure-g side-text">
      <div class="pure-u-1-2">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vulputate sapien in elit mattis, sit amet eleifend dui sodales. Nam ac risus leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque quam mi, cursus id massa at, lobortis finibus diam. Nullam elementum nisl urna, ut mattis sem volutpat ac.</p>
      </div>
      <div class="pure-u-1-2">
        <form class="pure-form" action="{% url 'create_restaurant' %}" method="post">
          <fieldset>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="pure-button pure-button-primary" value="Enviar" />
          </fieldset>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

Practica6/app/templates/forms/edit_restaurant.html
{% extends 'layout.html' %}
{% block body %}
  <script>
  $("document").ready(function(){
    $(".row").click(function(){
      $("#restaurant_id").attr("value", $(this).children(".restaurant_id").text());
    });

    $(".row").hover(function(){
      $(this).css('background-color', '#e8e9eb');
    }, function(){
      $(this).css('background-color', 'white');
    });
  });
  </script>
  <section class="default_section">
    <h1>Modifica tu restaurante</h1>
    <div class="pure-g side-text">
      <div class="pure-u-1-2">
        <h2>Selecciona el Restaurante</h2>
        <table class="pure-table">
          <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Barrio</th>
            <th>Dirección</th>
          </tr>
          {% for i, restaurant in restaurants %}
            <tr class="row">
              <td class="restaurant_id">{{ restaurant.restaurant_id }}</td>
              <td class="name">{{ restaurant.name }}</td>
              <td class="cuisine">{{ restaurant.cuisine }}</td>
              <td class="borough">{{ restaurant.borough }}</td>
              <td class="address">{{ restaurant.address.street }}</td>
            </tr>
          {% endfor %}
        </table>
        <div class="pagination">
          <span class="step-links">
              {% if restaurants.has_previous %}
                  <a class="pure-button pure-button-primary" href="?page={{ restaurants.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ restaurants.number }} of {{ restaurants.paginator.num_pages }}.
              </span>

              {% if restaurants.has_next %}
                  <a class="pure-button pure-button-primary" href="?page={{ restaurants.next_page_number }}">next</a>
              {% endif %}
          </span>
        </div>
      </div>
      <div class="pure-u-1-2">
        <h2>Datos</h2>
        <form class="pure-form" action="{% url 'edit_restaurant' %}" method="post">
          <fieldset>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="pure-button pure-button-primary" value="Enviar" />
          </fieldset>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

Practica6/app/templates/forms/find_restaurant.html
{% extends 'layout.html' %}
{% block body %}
  <script>
  var page;

  function appendData(parsed_data, n){
    $("#results *").remove();
    $("#results").append("<tr><th>Id</th><th>Nombre</th><th>Tipo</th><th>Código postal</th><th>Barrio</th></tr>")

    $.each( parsed_data, function( i, row ) {
      $("#results").append("<tr class=row id=tr"+ i +"></tr>");
      $("#tr"+i).append( "<td><a href=/restaurantes/find/detail/"+parsed_data[i].id+">" + parsed_data[i].id + "</a></td>" );
      $("#tr"+i).append( "<td>" + parsed_data[i].name + "</td>" );
      $("#tr"+i).append( "<td>" + parsed_data[i].cuisine + "</td>" );
      $("#tr"+i).append( "<td>" + parsed_data[i].zip + "</td>" );
      $("#tr"+i).append( "<td>" + parsed_data[i].borough + "</td>" );
    });
  }

  $('document').ready(function(){

    $('label[for=id_cuisine]').show();
    $('#id_cuisine').show();
    $('label[for=id_borough]').hide();
    $('#id_borough').hide();
    $('label[for=id_zipcode]').hide();
    $('#id_zipcode').hide();
    $('label[for=id_name]').hide();
    $('#id_name').hide();

    $('#find_button').click(function(){
      if ($('#id_field').val() == 'Name'){
        $.post(document.URL+"name", {'name': $("#id_name").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Cuisine') {
        $.post(document.URL+"cuisine", {'cuisine': $("#id_cuisine").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Borough') {
        $.post(document.URL+"borough", {'borough': $("#id_borough").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Zip') {
        $.post(document.URL+"zip", {'zip': $("#id_zipcode").val()}).done(function(data) {
          appendData(data);
        });
      }
      page = 1;
    });

    $('#next').click(function(){
      page += 1;
      if ($('#id_field').val() == 'Name'){
        $.post(document.URL+"name?page="+page, {'name': $("#id_name").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Cuisine') {
        $.post(document.URL+"cuisine?page="+page, {'cuisine': $("#id_cuisine").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Borough') {
        $.post(document.URL+"borough?page="+page, {'borough': $("#id_borough").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Zip') {
        $.post(document.URL+"zip?page="+page, {'zip': $("#id_zipcode").val()}).done(function(data) {
          appendData(data);
        });
      }
    });

    $('#previous').click(function(){
      page -= 1;
      if (page < 1){
        page = 1;
      }
      if ($('#id_field').val() == 'Name'){
        $.post(document.URL+"name?page="+page, {'name': $("#id_name").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Cuisine') {
        $.post(document.URL+"cuisine?page="+page, {'cuisine': $("#id_cuisine").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Borough') {
        $.post(document.URL+"borough?page="+page, {'borough': $("#id_borough").val()}).done(function(data) {
          appendData(data);
        });
      } else if ($('#id_field').val() == 'Zip') {
        $.post(document.URL+"zip?page="+page, {'zip': $("#id_zipcode").val()}).done(function(data) {
          appendData(data);
        });
      }
    });

    $('#id_field').change(function(){
      if ($(this).val() == 'Name'){
        $('label[for=id_cuisine]').hide();
        $('#id_cuisine').hide();
        $('label[for=id_borough]').hide();
        $('#id_borough').hide();
        $('label[for=id_zipcode]').hide();
        $('#id_zipcode').hide();
        $('label[for=id_name]').show();
        $('#id_name').show();
      } else if ($(this).val() == 'Cuisine') {
        $('label[for=id_cuisine]').show();
        $('#id_cuisine').show();
        $('label[for=id_borough]').hide();
        $('#id_borough').hide();
        $('label[for=id_zipcode]').hide();
        $('#id_zipcode').hide();
        $('label[for=id_name]').hide();
        $('#id_name').hide();
      } else if ($(this).val() == 'Borough') {
        $('label[for=id_cuisine]').hide();
        $('#id_cuisine').hide();
        $('label[for=id_borough]').show();
        $('#id_borough').show();
        $('label[for=id_zipcode]').hide();
        $('#id_zipcode').hide();
        $('label[for=id_name]').hide();
        $('#id_name').hide();
      } else if ($(this).val() == 'Zip') {
        $('label[for=id_cuisine]').hide();
        $('#id_cuisine').hide();
        $('label[for=id_borough]').hide();
        $('#id_borough').hide();
        $('label[for=id_zipcode]').show();
        $('#id_zipcode').show();
        $('label[for=id_name]').hide();
        $('#id_name').hide();
      }
    });
  });
  </script>
  <section class="default_section">
    <h1>Busca tu restaurante</h1>
    <div class="pure-g side-text">
      <div class="pure-u-1-2">
        <h2>Selecciona el Restaurante</h2>
        <table id="results" class="pure-table">
          <tr>
            <tr><th>Id</th><th>Nombre</th><th>Tipo</th><th>Código postal</th><th>Barrio</th></tr>
          </tr>
        </table>
        <div class="pagination">
          <span class="step-links">
                  <button class="pure-button pure-button-primary" id="previous">previous</button>
                  <button class="pure-button pure-button-primary" id="next">next</button>
          </span>
        </div>
      </div>
      <div class="pure-u-1-2">
        <h2>Datos</h2>
        <div class="pure-form">
          <fieldset>
            {% csrf_token %}
            {{ form.as_p }}
            <button id="find_button" class="pure-button pure-button-primary">Buscar</button>
          </fieldset>
        </div>
      </div>
    </div>
  </section>
{% endblock %}